// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Omnichannel.Infrastructure;

#nullable disable

namespace Omnichannel.Migrations
{
    [DbContext(typeof(OmnichannelDbContext))]
    [Migration("20260408142029_AddFeaturedPerfumesSeed")]
    partial class AddFeaturedPerfumesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Omnichannel.Models.BankTransferPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AppliedVoucherSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QrUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.ToTable("BankTransferPayments", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Floral"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Woody"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Fresh"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Designer"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Niche"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Luxury"
                        });
                });

            modelBuilder.Entity("Omnichannel.Models.ChannelOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SalesChannelId");

                    b.ToTable("ChannelOrders", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.ChannelProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfumeId");

                    b.HasIndex("SalesChannelId", "PerfumeId")
                        .IsUnique();

                    b.ToTable("ChannelProducts", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerfumeId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<string>("PerfumeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.Perfume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandStory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Concentration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("TopNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeOptions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Gender");

                    b.ToTable("Perfumes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseNotes = "Musk, Vanilla",
                            Brand = "KP Luxury",
                            BrandStory = "Crafted for graceful evenings.",
                            CategoryId = 1,
                            Concentration = "EDP",
                            Description = "Floral signature with elegant warm base.",
                            Gender = "Nữ",
                            ImageUrl = "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80",
                            MiddleNotes = "Rose, Jasmine",
                            Name = "Golden Bloom",
                            Origin = "France",
                            Price = 2159760m,
                            RowVersion = new byte[0],
                            StockQuantity = 120,
                            TopNotes = "Bergamot, Orange Blossom",
                            VolumeOptions = "30ml:0.7,50ml:1.0,100ml:1.6"
                        },
                        new
                        {
                            Id = 2,
                            BaseNotes = "Cedarwood, Amber",
                            Brand = "KP Luxury",
                            BrandStory = "A bold and structured masculine trail.",
                            CategoryId = 2,
                            Concentration = "EDT",
                            Description = "Woody aromatic blend for modern professionals.",
                            Gender = "Nam",
                            ImageUrl = "https://images.unsplash.com/photo-1595425977377-9a6f0f0fef87?auto=format&fit=crop&w=800&q=80",
                            MiddleNotes = "Lavender, Sage",
                            Name = "Midnight Cedar",
                            Origin = "Italy",
                            Price = 2388000m,
                            RowVersion = new byte[0],
                            StockQuantity = 90,
                            TopNotes = "Grapefruit, Pepper",
                            VolumeOptions = "50ml:1.0,100ml:1.6"
                        },
                        new
                        {
                            Id = 3,
                            BaseNotes = "Cedar, White Musk",
                            Brand = "KP Luxury",
                            BrandStory = "Freshness designed for daily confidence.",
                            CategoryId = 3,
                            Concentration = "EDP",
                            Description = "Fresh unisex scent inspired by coastal mornings.",
                            Gender = "Unisex",
                            ImageUrl = "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=800&q=80",
                            MiddleNotes = "Neroli, Green Tea",
                            Name = "Ocean Whisper",
                            Origin = "Spain",
                            Price = 1896000m,
                            RowVersion = new byte[0],
                            StockQuantity = 140,
                            TopNotes = "Lemon, Sea Salt",
                            VolumeOptions = "30ml:0.7,50ml:1.0,100ml:1.6"
                        },
                        new
                        {
                            Id = 4,
                            BaseNotes = "Gỗ tuyết tùng, đàn hương, hổ phách",
                            Brand = "Chanel",
                            BrandStory = "Biểu tượng nam tính hiện đại của Chanel, đậm chất lịch lãm và tự do.",
                            CategoryId = 4,
                            Concentration = "Parfum",
                            Description = "Một mùi hương mạnh mẽ, tinh tế với sự kết hợp của gỗ tuyết tùng, đàn hương và cam quýt.",
                            Gender = "Nam",
                            ImageUrl = "https://perfume-store.com/images/chanel-bleu-1.jpg",
                            MiddleNotes = "Gừng, nhục đậu khấu, hoa hồng",
                            Name = "Bleu de Chanel Parfum",
                            Origin = "France",
                            Price = 3850000m,
                            RowVersion = new byte[0],
                            StockQuantity = 25,
                            TopNotes = "Cam quýt, chanh vàng, bưởi",
                            VolumeOptions = "50ml:1.0,100ml:1.6"
                        },
                        new
                        {
                            Id = 5,
                            BaseNotes = "Gỗ đàn hương, da thuộc, xạ hương",
                            Brand = "Le Labo",
                            BrandStory = "Một hương thơm unisex mang tính biểu tượng, được yêu thích bởi giới mộ điệu.",
                            CategoryId = 5,
                            Concentration = "EDP",
                            Description = "Biểu tượng của sự cá tính với mùi hương đặc trưng của gỗ đàn hương, bạch đậu khấu và hoa violet.",
                            Gender = "Unisex",
                            ImageUrl = "https://perfume-store.com/images/lelabo-santal-1.jpg",
                            MiddleNotes = "Diên vĩ, papyrus",
                            Name = "Le Labo Santal 33",
                            Origin = "United States",
                            Price = 5200000m,
                            RowVersion = new byte[0],
                            StockQuantity = 10,
                            TopNotes = "Bạch đậu khấu, violet",
                            VolumeOptions = "50ml:1.0"
                        },
                        new
                        {
                            Id = 6,
                            BaseNotes = "Hoắc hương, cỏ vetiver",
                            Brand = "Narciso Rodriguez",
                            BrandStory = "Tinh tế, nữ tính và đầy gợi cảm - dấu ấn đặc trưng của Narciso Rodriguez.",
                            CategoryId = 4,
                            Concentration = "EDP",
                            Description = "Mùi hương quyến rũ bậc nhất với nốt xạ hương chủ đạo, kết hợp cùng hoa hồng và đào.",
                            Gender = "Nữ",
                            ImageUrl = "https://perfume-store.com/images/narciso-pink-1.jpg",
                            MiddleNotes = "Xạ hương, hổ phách",
                            Name = "Narciso Rodriguez For Her",
                            Origin = "France",
                            Price = 2950000m,
                            RowVersion = new byte[0],
                            StockQuantity = 40,
                            TopNotes = "Hoa hồng, đào",
                            VolumeOptions = "50ml:1.0,100ml:1.6"
                        },
                        new
                        {
                            Id = 7,
                            BaseNotes = "Gỗ sồi, khói, long diên hương",
                            Brand = "Creed",
                            BrandStory = "Một trong những mùi hương nam giới kinh điển và quyền lực nhất thế giới niche-luxury.",
                            CategoryId = 6,
                            Concentration = "EDP",
                            Description = "Ông hoàng của dòng nước hoa nam với hương dứa nướng, khói và long diên hương.",
                            Gender = "Nam",
                            ImageUrl = "https://perfume-store.com/images/creed-aventus-1.jpg",
                            MiddleNotes = "Hoa nhài, hoắc hương",
                            Name = "Creed Aventus",
                            Origin = "United Kingdom",
                            Price = 7500000m,
                            RowVersion = new byte[0],
                            StockQuantity = 5,
                            TopNotes = "Dứa, bergamot, lý chua đen",
                            VolumeOptions = "50ml:1.0,100ml:1.6"
                        },
                        new
                        {
                            Id = 8,
                            BaseNotes = "Xạ hương trắng",
                            Brand = "Dior",
                            BrandStory = "Một bó hoa thanh lịch dành cho phong cách nữ tính, nhẹ nhàng và hiện đại.",
                            CategoryId = 4,
                            Concentration = "EDT",
                            Description = "Một bó hoa tươi thắm với hương mẫu đơn và hoa hồng Damask nhẹ nhàng, thanh khiết.",
                            Gender = "Nữ",
                            ImageUrl = "https://perfume-store.com/images/dior-blooming-1.jpg",
                            MiddleNotes = "Mẫu đơn, hoa hồng Damask",
                            Name = "Miss Dior Blooming Bouquet",
                            Origin = "France",
                            Price = 2150000m,
                            RowVersion = new byte[0],
                            StockQuantity = 15,
                            TopNotes = "Quýt hồng, cam bergamot",
                            VolumeOptions = "50ml:1.0"
                        });
                });

            modelBuilder.Entity("Omnichannel.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoOccurrenceScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecommendedPerfumeId")
                        .HasColumnType("int");

                    b.Property<int>("SourcePerfumeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoOccurrenceScore");

                    b.HasIndex("RecommendedPerfumeId");

                    b.HasIndex("SourcePerfumeId");

                    b.ToTable("Recommendations", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.SalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalesChannels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelName = "Website",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "https://ui-avatars.com/api/?name=Website&background=111&color=c5a059"
                        },
                        new
                        {
                            Id = 2,
                            ChannelName = "Shopee",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "https://cdn.worldvectorlogo.com/logos/shopee-2.svg"
                        },
                        new
                        {
                            Id = 3,
                            ChannelName = "Lazada",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/d/df/Lazada_Logo.png"
                        },
                        new
                        {
                            Id = 4,
                            ChannelName = "TikTok Shop",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "https://cdn-icons-png.flaticon.com/512/3046/3046121.png"
                        });
                });

            modelBuilder.Entity("Omnichannel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@kp-luxury.local",
                            FullName = "System Admin",
                            Password = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@kp-luxury.local",
                            FullName = "Demo User",
                            Password = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Role = "User",
                            Username = "userdemo"
                        });
                });

            modelBuilder.Entity("Omnichannel.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("SalesChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimitPerUser")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimitTotal")
                        .HasColumnType("int");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SalesChannelId");

                    b.ToTable("Vouchers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WELCOME10",
                            Description = "Giảm 10% cho đơn hàng đầu tiên",
                            DiscountType = "Percentage",
                            DiscountValue = 10m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxDiscountAmount = 100080m,
                            MinOrderValue = 360000m,
                            Name = "Welcome 10%",
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimitPerUser = 1,
                            UsageLimitTotal = 100,
                            VoucherType = "Order"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ORDER50K",
                            Description = "Giảm 50,000đ trên tổng đơn hàng",
                            DiscountType = "FixedAmount",
                            DiscountValue = 49920m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MinOrderValue = 480000m,
                            Name = "Order -50K",
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimitPerUser = 2,
                            UsageLimitTotal = 50,
                            VoucherType = "Order"
                        },
                        new
                        {
                            Id = 3,
                            Code = "VIP15",
                            Description = "Giảm 15% cho khách VIP trên website",
                            DiscountType = "Percentage",
                            DiscountValue = 15m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxDiscountAmount = 199920m,
                            MinOrderValue = 960000m,
                            Name = "VIP 15%",
                            SalesChannelId = 1,
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimitPerUser = 1,
                            UsageLimitTotal = 20,
                            VoucherType = "Order"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SHIP20K",
                            Description = "Giảm 20,000đ phí ship",
                            DiscountType = "FixedAmount",
                            DiscountValue = 19920m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MinOrderValue = 288000m,
                            Name = "Ship -20K",
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimitPerUser = 3,
                            UsageLimitTotal = 100,
                            VoucherType = "Shipping"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SHIP10",
                            Description = "Giảm 10% phí ship, tối đa 50,000đ",
                            DiscountType = "Percentage",
                            DiscountValue = 10m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxDiscountAmount = 49920m,
                            MinOrderValue = 480000m,
                            Name = "Ship 10%",
                            SalesChannelId = 1,
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimitPerUser = 2,
                            UsageLimitTotal = 75,
                            VoucherType = "Shipping"
                        });
                });

            modelBuilder.Entity("Omnichannel.Models.VoucherRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "VoucherId")
                        .IsUnique();

                    b.HasIndex("VoucherId", "UserId");

                    b.ToTable("VoucherRedemptions", (string)null);
                });

            modelBuilder.Entity("Omnichannel.Models.ChannelOrder", b =>
                {
                    b.HasOne("Omnichannel.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omnichannel.Models.SalesChannel", "SalesChannel")
                        .WithMany()
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("Omnichannel.Models.ChannelProduct", b =>
                {
                    b.HasOne("Omnichannel.Models.Perfume", "Perfume")
                        .WithMany()
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omnichannel.Models.SalesChannel", "SalesChannel")
                        .WithMany()
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfume");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("Omnichannel.Models.Order", b =>
                {
                    b.HasOne("Omnichannel.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omnichannel.Models.OrderItem", b =>
                {
                    b.HasOne("Omnichannel.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omnichannel.Models.Perfume", b =>
                {
                    b.HasOne("Omnichannel.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Omnichannel.Models.Recommendation", b =>
                {
                    b.HasOne("Omnichannel.Models.Perfume", "RecommendedPerfume")
                        .WithMany()
                        .HasForeignKey("RecommendedPerfumeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnichannel.Models.Perfume", "SourcePerfume")
                        .WithMany()
                        .HasForeignKey("SourcePerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecommendedPerfume");

                    b.Navigation("SourcePerfume");
                });

            modelBuilder.Entity("Omnichannel.Models.Voucher", b =>
                {
                    b.HasOne("Omnichannel.Models.SalesChannel", "SalesChannel")
                        .WithMany()
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("Omnichannel.Models.VoucherRedemption", b =>
                {
                    b.HasOne("Omnichannel.Models.Voucher", "Voucher")
                        .WithMany("Redemptions")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Omnichannel.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Omnichannel.Models.Voucher", b =>
                {
                    b.Navigation("Redemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
